[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "geogals"
version = "0.1.8"
description = "A publicly available repository for using geostatistical methods on real and simulated galaxy data."
readme = "README.rst"
requires-python = ">=3.7"
authors = [
  {name = "Benjamin Metha", email = "methab@student.unimelb.edu.au"}
]
maintainers = [
  {name = "Benjamin Metha", email = "methab@student.unimelb.edu.au"}
]
license = {text = "MIT"}
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
    "astropy>=7.0.1",
    "emcee>=3.0.0",
    "extinction",
    "gpytorch",
    "matplotlib",
    "numpy<2",
    "photutils",
    "scipy>=1.15.0",
    "statsmodels>=0.14.4",
    "scikit-learn>=1.6.0",
    "scikit-image",
    "torch"
]

[project.optional-dependencies]
dev = [
  "coverage",
  "mypy",
  "pytest",
  "ruff"
]

doc = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
    "sphinxcontrib-napoleon"
]

[project.urls]
bugs = "https://github.com/astrobenji/geogals/issues"
changelog = "https://github.com/astrobenji/geogals/blob/master/changelog.md"
homepage = "https://github.com/astrobenji/geogals"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.mypy]
files = "."
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"
